# This file is sourced before .zshrc and will always be sourced
# ie for interactive/non-interactive, and login/non-login shells
# It is sourced before all other zsh dot files so we should be
# careful setting our PATH here as it may be overridden by
# anything in those files.

