HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
bindkey -v
zstyle :compinstall filename '$HOME/.zshrc'
autoload -Uz compinit
compinit

export NVM_DIR=~/.nvm

export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

# Load nvm
source $(brew --prefix nvm)/nvm.sh

# Set options
source ~/.zsh/setopt.zsh

# Set aliases
source ~/.zsh/alias.zsh

# Load plugins with zplug
source ~/.zsh/plugins.zsh

if ! zplug check; then
    zplug install
fi
