# This file is sourced for interactive shells only (both login and non-login)
# It is sourced after .zshenv
# If this is a login shell, then .zprofile will be sourced directly before it
# and .zlogin will be sourced after

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000

# Reduce key sequence delay, mostly to get out of vi normal mode faster
# Default is 400ms, we are reducing to 10ms
KEYTIMEOUT=1

# Set default java version to java8 for use with scala
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

# Export environment variables for pyenv and rbenv
# These must use $HOME, not ~
export PYENV_ROOT="$HOME/.pyenv"
export RBENV_ROOT="$HOME/.rbenv"

# Lazy load nvm so it doesn't load when you open a new shell
export NVM_LAZY_LOAD=true

# Automatically switch to node version in local .nvmrc
export NVM_AUTO_USE=true

# Bind up and down keys to search history with currently entered prompt text
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# Always use emacs mode
bindkey -e

# Rebind ctrl K to get it working in tmux
bindkey \^K kill-line

zstyle :compinstall filename '$HOME/.zshrc'
autoload -Uz compinit
compinit

export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

# Set options
source ~/.zsh/setopt.zsh

# Load scripts
source ~/.zsh/scripts.zsh

# Set aliases
source ~/.zsh/alias.zsh

# Prepend pyenv and rbenv shims to PATH, this is not done in 
# .zshenv as .zshenv is sourced first, so we would not be
# able to guarantee that the shims are first on the PATH
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

if command -v rbenv 1>/dev/null 2>&1; then
  eval "$(rbenv init -)"
fi

# Add path to gnu-sed
PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"

# Add brews sbin to the path
export PATH="/usr/local/sbin:$PATH"

# Load plugins with zplug
source ~/.zsh/plugins.zsh

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=239'

if ! zplug check; then
    zplug install
fi

# Set fzf default command so it shows hidden files excluding .git folder and node_modues
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
