# installs macOS apps using brew

# formulae repositories
tap "homebrew/core"
tap "homebrew/bundle"
tap "mongodb/brew"

# cask, for installing non-cli apps that are not on the app store
brew "cask"

# replace builtin macos sed with gnu-sed
brew "gnu-sed"

# replace system git
brew "git"

# replace system grep
brew "grep"

# mas-cli, which installs app store apps 
brew "mas"

# neovim, a refactored, async vim
brew "neovim"

# ruby version manager
brew "rbenv"

# python version manager
brew "pyenv"

# pyenv / virtualenv integration 
brew "pyenv-virtualenv", args: ["HEAD"]

# readline pyenv requirement
brew "readline"

# find-in-file functionality
brew "the_silver_searcher"

# simplified man page util
brew "tldr"

# app to show n deep directory hierarchies
brew "tree"

# Replace vim
brew "vim"

# file watchers 
brew "watch"
brew "watchman"

# file downloader
brew "wget"

# xz pyenv requirement
brew "xz"

# npm replacement yarn
brew "yarn", args: ["ignore-dependencies"]

# zsh plugin manager
brew "zplug"

# z shell
brew "zsh"

# mongodb

brew "mongodb-community"